-- ====================================================================
-- Snowflake Foundational Infrastructure and RBAC Setup
-- ====================================================================

-- 1. Create Database
CREATE DATABASE IF NOT EXISTS CREDIT_UNION_DB;

-- 2. Create Virtual Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 300 
  AUTO_RESUME = TRUE;

-- 3. Create Schemas
CREATE SCHEMA IF NOT EXISTS CREDIT_UNION_DB.RAW;
CREATE SCHEMA IF NOT EXISTS CREDIT_UNION_DB.ANALYTICS;

-- 4. Create Roles
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;

-- 5. Grant DATA_ENGINEER full ALL PRIVILEGES access
GRANT ALL PRIVILEGES ON DATABASE CREDIT_UNION_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA CREDIT_UNION_DB.RAW TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE CREDIT_UNION_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE CREDIT_UNION_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE CREDIT_UNION_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE CREDIT_UNION_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE CREDIT_UNION_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE CREDIT_UNION_DB TO ROLE DATA_ENGINEER;
GRANT ALL PRIVILEGES ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ENGINEER;

-- 6. Grant DATA_ANALYST Strict Analytics Access
GRANT USAGE ON DATABASE CREDIT_UNION_DB TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_ANALYST;

-- 7. Grant DATA_SCIENTIST Raw and Analytics Access
GRANT USAGE ON DATABASE CREDIT_UNION_DB TO ROLE DATA_SCIENTIST;
GRANT USAGE ON SCHEMA CREDIT_UNION_DB.RAW TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIT_UNION_DB.RAW TO ROLE DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIT_UNION_DB.RAW TO ROLE DATA_SCIENTIST;
GRANT USAGE ON SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL VIEWS IN SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_SCIENTIST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_SCIENTIST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA CREDIT_UNION_DB.ANALYTICS TO ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATA_SCIENTIST;

-- 8. Grant Roles to Primary User
GRANT ROLE DATA_ENGINEER TO USER RSGODWIN;
GRANT ROLE DATA_ANALYST TO USER RSGODWIN;
GRANT ROLE DATA_SCIENTIST TO USER RSGODWIN;
